---
inputs:
- name: in

outputs:
- name: out

params:
  COUNT: 1

platform: linux
image_resource:
  type: docker-image
  source:
    repository: "alpine"

run:
  path: "/bin/ash"
  args:
  - "-c"
  - |
    ping -c $COUNT $(cat in/address.txt) > out/output.log
