---
inputs:
- name: inputdir

outputs:
- name: outputdir

params:
  COUNT: 1

platform: linux
image_resource:
  type: docker-image
  source:
    repository: "alpine"

run:
  path: "/bin/ash"
  args:
  - "-c"
  - |
    ping -c $COUNT $(cat inputdir/address.txt) > outputdir/output.log
