---
inputs:
- name: e2e-repo

platform: linux
image_resource:
  type: docker-image
  source:
    repository: "registry:5000/todo-run-e2e"
    insecure_registries: ["registry:5000"]

run:
  path: /bin/bash
  args:
  - -euc
  - |
    cd e2e-repo/demo/frontend
    mv /tmp/node_modules .
    APP_URL=http://todo.ci.kube.daniel yarn e2e-ci
