inputs:
- name: repo
outputs:
- name: build

platform: linux
image_resource:
  type: docker-image
  source:
    repository: "registry:5000/backend-image"
    insecure_registries: ["registry:5000"]

run:
  path: repo/demo/ci/scripts/test-and-build-backend.sh
