---
inputs:
- name: repo
outputs:
- name: build

platform: linux
image_resource:
  type: docker-image
  source:
    repository: "registry:5000/todo-build-backend"
    insecure_registries: ["registry:5000"]

run:
  path: /bin/bash
  args:
  - -exc
  - |
    GIT_DIR=$PWD/repo/.git
    SOURCE_DIR=$PWD/repo/demo/backend
    OUTPUT_DIR=$PWD/build
    COMMIT_REF=$(cat $GIT_DIR/ref || echo test)
    cd $SOURCE_DIR

    mvn -s /usr/share/maven/ref/settings.xml \
        clean package \
        -DdisablexmlReport=true \
        -Dsurefire.useFile=false \
        -Dlogging.level.org.springframework=WARN

    mkdir -p OUTPUT_DIR
    cp -R target "$OUTPUT_DIR"
    cp Dockerfile "$OUTPUT_DIR"
    echo "${COMMIT_REF}" | tee "$OUTPUT_DIR/tags.txt"
