---
inputs:
- name: repo
outputs:
- name: build

platform: linux
image_resource:
  type: docker-image
  source:
    repository: "registry:5000/todo-build-frontend"
    insecure_registries: ["registry:5000"]

run:
  path: /bin/bash
  args:
  - -euc
  - |
    OUTPUT_DIR=$PWD/build
    GIT_REPO="$PWD/repo/.git"
    COMMIT_REF=$(cat $GIT_REPO/ref || echo local)
    CURRENT_DATE=$(date +%Y-%m-%d-%H%M)

    cd repo/demo/frontend
    mv /tmp/node_modules .
    CI=true yarn test
    yarn build

    mkdir -p $OUTPUT_DIR
    cp -R build $OUTPUT_DIR
    cp Dockerfile "$OUTPUT_DIR"
    echo "${CURRENT_DATE}_${COMMIT_REF}" | tee "$OUTPUT_DIR/tags.txt"
