---
applications:
- name: backend
  buildpacks:
  - java_buildpack_offline
  instances: 1
  memory: 768M
  disk_quota: 256M
  routes:
  - route: todo.dev.cfdev.sh/api
  path: backend/todo.jar

- name: web-app
  buildpacks:
  - staticfile_buildpack
  instances: 1
  memory: 64M
  disk_quota: 256M
  routes:
  - route: todo.dev.cfdev.sh
  path: frontend
