config:
- &git-config
  uri: git@git.host.daniel:~/concourse-demo.git
  private_key: {{ssh-key}}
  branch: master

- &cf-config
  api: https://api.local.pcfdev.io
  username: admin
  password: admin
  organization: pcfdev-org
  skip_cert_check: true

- &s3-config
  access_key_id: minio
  secret_access_key: changeme
  endpoint: http://minio:9000/
  skip_ssl_verification: true

resources:
- name: backend-repo
  type: git
  source:
    <<: *git-config
    paths:
    - demo/backend
    - demo/ci/tasks/test-and-build-backend.yml
    - demo/ci/scripts/test-and-build-backend.sh
    - demo/ci/manifests/backend.yml

- name: frontend-repo
  type: git
  source:
    <<: *git-config
    paths:
    - demo/frontend
    - demo/ci/tasks/test-and-build-frontend.yml
    - demo/ci/scripts/test-and-build-frontend.sh
    - demo/ci/manifests/frontend.yml

- name: cf-dev
  type: cf
  source:
    <<: *cf-config
    space: ci

- name: backend-bucket
  type: s3
  source:
    <<: *s3-config
    bucket: todo-backend
    regexp: backend-(.*).jar

- name: frontend-bucket
  type: s3
  source:
    <<: *s3-config
    bucket: todo-frontend
    regexp: frontend-(.*).tgz

jobs:
- name: backend
  plan:
  - get: repo
    resource: backend-repo
    trigger: true
  - task: build
    file: repo/demo/ci/tasks/test-and-build-backend.yml
  - put: cf-dev
    params:
      manifest: repo/demo/ci/manifests/backend.yml
      path: build/backend-*.jar
  - put: backend-bucket
    params:
      file: build/backend-*.jar

- name: frontend
  plan:
  - get: repo
    resource: frontend-repo
    trigger: true
  - task: test
    file: repo/demo/ci/tasks/test-and-build-frontend.yml
  - put: cf-dev
    params:
      manifest: repo/demo/ci/manifests/frontend.yml
      path: build/dist
  - put: frontend-bucket
    params:
      file: build/frontend-*.tgz
