config:
- &git-config
  uri: git@git:~/concourse.git
  private_key: ((id-rsa-git))
  branch: master

resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: "registry:5000/zlabjp/kubernetes-resource"
    insecure_registries:
    - "registry:5000"

resources:
- name: backend-repo
  type: git
  source:
    <<: *git-config
    paths:
    - demo/backend
    - demo/ci/tasks/test-and-build-backend.yml
    - demo/ci/manifests/backend.yml

- name: frontend-repo
  type: git
  source:
    <<: *git-config
    paths:
    - demo/frontend
    - demo/ci/tasks/test-and-build-frontend.yml
    - demo/ci/manifests/frontend.yml

- name: e2e-repo
  type: git
  source:
    <<: *git-config
    paths:
    - demo/frontend/e2e
    - demo/frontend/*.json
    - demo/frontend/*.lock
    - demo/kubernetes
    - demo/ci/tasks/create-manifest.yml
    - demo/ci/tasks/run-e2e.yml

- name: backend-image
  type: docker-image
  source:
    insecure_registries: ["registry:5000"]
    repository: "registry:5000/todo-backend"

- name: frontend-image
  type: docker-image
  source:
    insecure_registries: ["registry:5000"]
    repository: "registry:5000/todo-frontend"

- name: kubernetes
  type: kubernetes
  source:
    kubeconfig: |
      ((kubeconfig))

jobs:
- name: backend
  plan:
  - get: repo
    resource: backend-repo
    trigger: true
  - task: build
    file: repo/demo/ci/tasks/test-and-build-backend.yml
  - put: backend-image
    params:
      build: build
      additional_tags: build/tags.txt

- name: frontend
  plan:
  - get: repo
    resource: frontend-repo
    trigger: true
  - task: build
    file: repo/demo/ci/tasks/test-and-build-frontend.yml
  - put: frontend-image
    params:
      build: build
      additional_tags: build/tags.txt

- name: end-to-end
  plan:
  - in_parallel:
    - get: backend-repo
      trigger: true
      passed: 
      - backend
    - get: frontend-repo
      trigger: true
      passed: 
      - frontend
  - get: e2e-repo
  - task: create-manifest
    file: e2e-repo/demo/ci/tasks/create-manifest.yml
  - put: deploy-to-kubernetes
    resource: kubernetes
    params:
      kubectl: apply -f manifests/todo.yaml
      wait_until_ready: 120
      wait_until_ready_interval: 10
  - task: run-tests
    file: e2e-repo/demo/ci/tasks/run-e2e.yml
