config:
- &git-config
  uri: git@git:~/concourse.git
  private_key: ((id-rsa-git))
  branch: master

- &cf-config
  api: ((cf.api))
  username: ((cf.username))
  password: ((cf.password))
  organization: cfdev-org
  skip_cert_check: true

- &s3-config
  access_key_id: ((minio.id))
  secret_access_key: ((minio.secret))
  endpoint: ((minio.api))
  skip_ssl_verification: true

resources:
- name: backend-repo
  type: git
  source:
    <<: *git-config
    paths:
    - demo/backend
    - demo/ci/tasks/test-and-build-backend.yml
    - demo/ci/scripts/test-and-build-backend.sh
    - demo/ci/manifests/backend.yml

- name: frontend-repo
  type: git
  source:
    <<: *git-config
    paths:
    - demo/frontend
    - demo/ci/tasks/test-and-build-frontend.yml
    - demo/ci/scripts/test-and-build-frontend.sh
    - demo/ci/manifests/frontend.yml

- name: e2e-repo
  type: git
  source:
    <<: *git-config
    paths:
    - demo/frontend/e2e
    - demo/frontend/*.json
    - demo/frontend/*.lock
    - demo/ci/tasks/run-e2e.yml
    - demo/ci/scripts/run-e2e.sh

- name: release-repo
  type: git
  source:
    <<: *git-config
    paths:
    - demo/ci/manifests
    - demo/ci/tasks/package-release.yml
    - demo/ci/scripts/package-release.sh

- name: cf-dev
  type: cf
  source:
    <<: *cf-config
    space: ci

- name: cf-prod
  type: cf
  source:
    <<: *cf-config
    space: prod

- name: backend-bucket
  type: s3
  source:
    <<: *s3-config
    bucket: todo-backend
    regexp: backend-(.*).jar

- name: frontend-bucket
  type: s3
  source:
    <<: *s3-config
    bucket: todo-frontend
    regexp: frontend-(.*).tgz

- name: release-bucket
  type: s3
  source:
    <<: *s3-config
    bucket: todo-app
    regexp: todo-(.*).tgz

# Semantic versioning resources, to bump version numbers automatically
- name: release-version
  type: semver
  source:
    driver: s3
    <<: *s3-config
    bucket: todo-version
    key: version
    initial_version: "1.0.0"

jobs:
- name: backend
  plan:
  - get: repo
    resource: backend-repo
    trigger: true
  - task: build
    file: repo/demo/ci/tasks/test-and-build-backend.yml
  - put: cf-dev
    params:
      manifest: repo/demo/ci/manifests/backend.yml
      path: build/backend-*.jar
  - put: backend-bucket
    params:
      file: build/backend-*.jar

- name: frontend
  plan:
  - get: repo
    resource: frontend-repo
    trigger: true
  - task: test
    file: repo/demo/ci/tasks/test-and-build-frontend.yml
  - put: cf-dev
    params:
      manifest: repo/demo/ci/manifests/frontend.yml
      path: build/dist
  - put: frontend-bucket
    params:
      file: build/frontend-*.tgz

- name: e2e
  plan:
  - get: repo
    resource: e2e-repo
    trigger: true
  - get: frontend-bucket
    passed: [frontend]
    trigger: true
  - get: backend-bucket
    passed: [backend]
    trigger: true
  - task: test
    file: repo/demo/ci/tasks/run-e2e.yml


- name: release
  plan:
  - in_parallel:
    - get: frontend-bucket
      passed: [e2e]
      trigger: true
      params:
        unpack: true
    - get: backend-bucket
      passed: [e2e]
      trigger: true
    - get: release-version
    - get: repo
      resource: release-repo
      trigger: true
  - task: repackage
    file: repo/demo/ci/tasks/package-release.yml
  - in_parallel:
    - put: cf-prod
      params:
        manifest: prod/manifest.yml
    - put: release-bucket
      params:
        file: release/todo-*.tgz
    - put: release-version
      params:
        bump: patch
