config:
- &git-config
  uri: git@172.19.0.1:~/concourse-demo.git
  private_key: {{ssh-key}}
  branch: master

resources:
- name: backend-image-repo
  type: git
  source:
    <<: *git-config
    paths:
    - demo/backend/pom.xml
    - demo/ci/dockerfiles/backend-dockerfile

- name: frontend-image-repo
  type: git
  source:
    <<: *git-config
    paths:
    - demo/frontend/package.json
    - demo/frontend/yarn.lock
    - demo/ci/dockerfiles/frontend-dockerfile

- name: e2e-image-repo
  type: git
  source:
    <<: *git-config
    paths:
    - demo/ci/dockerfiles/e2e-dockerfile

# Last, the docker images in which to run jobs
- name: backend-image
  type: docker-image
  source:
    insecure_registries: ["registry:5000"]
    repository: "registry:5000/backend-image"

- name: frontend-image
  type: docker-image
  source:
    insecure_registries: ["registry:5000"]
    repository: "registry:5000/frontend-image"

- name: e2e-image
  type: docker-image
  source:
    insecure_registries: ["registry:5000"]
    repository: "registry:5000/e2e-image"

jobs:
- name: build-backend-image
  plan:
  - get: repo
    resource: backend-image-repo
  - put: backend-image
    params:
      build: repo
      dockerfile: repo/demo/ci/dockerfiles/backend-dockerfile

- name: build-frontend-image
  plan:
  - get: repo
    resource: frontend-image-repo
  - put: frontend-image
    params:
      build: repo
      dockerfile: repo/demo/ci/dockerfiles/frontend-dockerfile

- name: build-e2e-image
  plan:
  - get: repo
    resource: e2e-image-repo
  - put: e2e-image
    params:
      build: repo
      dockerfile: repo/demo/ci/dockerfiles/e2e-dockerfile
