---
inputs:
- name: repo
- name: backend-bucket
- name: frontend-bucket
- name: release-version
outputs:
- name: prod
- name: release

platform: linux
image_resource:
  type: docker-image
  source:
    skip_download: false
    repository: "registry:5000/alpine"
    insecure_registries: ["registry:5000"]

run:
  path: /bin/ash
  args:
  - -euc
  - |
    PROD_FOLDER=$PWD/prod
    RELEASE_FOLDER=$PWD/release
    TAR_FOLDER=/tmp/tar
    VERSION=$(cat release-version/version)
    TAR_FILE="$RELEASE_FOLDER/todo-$VERSION.tgz"
    mkdir -p $TAR_FOLDER/frontend
    mkdir -p $TAR_FOLDER/backend
    # Tar up resources
    cp -R frontend-bucket/* $TAR_FOLDER/frontend
    cp backend-bucket/*.jar $TAR_FOLDER/backend/todo.jar
    tar -czf $TAR_FILE -C $TAR_FOLDER .
    mv $TAR_FILE $RELEASE_FOLDER
    # Prepare release for deploy
    mkdir -p $PROD_FOLDER/frontend
    mkdir -p $PROD_FOLDER/backend
    cp -R frontend-bucket/* $PROD_FOLDER/frontend
    cp backend-bucket/*.jar $PROD_FOLDER/backend/todo.jar
    cp repo/demo/ci/manifests/prod.yml $PROD_FOLDER/manifest.yml
