version: '3'

services:
  concourse-db:
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse
      POSTGRES_PASSWORD: changeme
      PGDATA: /database

  concourse-web:
    image: concourse/concourse
    links: [concourse-db]
    command: web
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    volumes: ["./keys/web:/concourse-keys"]
    restart: unless-stopped # required so that it retries until concourse-db comes up
    environment:
      CONCOURSE_NO_REALLY_I_DONT_WANT_ANY_AUTH: "true"
      CONCOURSE_EXTERNAL_URL: "${CONCOURSE_EXTERNAL_URL}"
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse
      CONCOURSE_POSTGRES_PASSWORD: changeme
      CONCOURSE_POSTGRES_DATABASE: concourse

  concourse-worker:
    image: concourse/concourse
    privileged: true
    links: [concourse-web, registry]
    depends_on: [concourse-web, registry]
    command: worker
    dns:
    - "172.19.0.1"
    - "8.8.8.8"
    volumes:
    - "./keys/worker:/concourse-keys"
    - "./worker-state:/worker-state"
    environment:
      CONCOURSE_TSA_HOST: concourse-web

  registry:
    image: registry:2
    depends_on: [concourse-web]
    volumes:
      - "registry:/var/lib/registry"
    ports:
      - "5000:5000"

  minio:
    image: minio/minio
    depends_on: [concourse-web]
    volumes:
    - minio-data:/export
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: changeme
    command: server /export


volumes:
  registry:
    external: true
  minio-data:
