config:
- &git-config
  uri: https://github.com/Kehrlann/concourse-demo.git
  branch: master

resources:
- name: backend-image-repo
  type: git
  source:
    <<: *git-config
    paths: [demo/backend/pom.xml, demo/ci/dockerfiles/backend-dockerfile]

- name: backend-repo
  type: git
  source:
    <<: *git-config
    paths: [demo/backend, demo/ci/tasks/build-backend.yml]

- name: backend-image
  type: docker-image
  source:
    insecure_registries: ["registry:5000"]
    repository: "registry:5000/backend-image"

jobs:
- name: build-backend-image
  plan:
  - get: repo
    resource: backend-image-repo
    trigger: true
  - put: backend-image
    params:
      build: repo
      dockerfile: repo/demo/ci/dockerfiles/backend-dockerfile

- name: backend
  plan:
  - get: repo
    resource: backend-repo
    trigger: true
  - get: backend-image
  - task: test-task
    image: backend-image
    config:
      platform: linux
      inputs:
      - name: repo
      run:
        path: /bin/bash
        args:
          - "-c"
          - |
            cd repo/demo/backend && \
            mvn test -s /usr/share/maven/ref/settings.xml
