#------------------------------------------------------------------------------
#
# Global config :
# These are just yaml labels that can be reused elsewhere in the file, to allow
# reuse of common values. They are not concourse specific.
#
#------------------------------------------------------------------------------
config:
- &git-config
  uri: git@172.19.0.1:~/concourse-demo.git
  private_key: {{ssh-key}}
  branch: master


#------------------------------------------------------------------------------
#
# Concourse resources :
# Here are the inputs and outputs of all jobs defined in this pipeline.
#
#------------------------------------------------------------------------------
resources:
- name: backend-image-repo
  type: git
  source:
    <<: *git-config
    paths:
    - demo/backend/pom.xml
    - demo/ci/dockerfiles/backend-dockerfile

- name: frontend-image-repo
  type: git
  source:
    <<: *git-config
    paths:
    - demo/frontend/package.json
    - demo/frontend/yarn.lock
    - demo/ci/dockerfiles/frontend-dockerfile

- name: e2e-image-repo
  type: git
  source:
    <<: *git-config
    paths:
    - demo/ci/dockerfiles/e2e-dockerfile

- name: backend-image
  type: docker-image
  source:
    insecure_registries: ["registry:5000"]
    repository: "registry:5000/backend-image"

- name: frontend-image
  type: docker-image
  source:
    insecure_registries: ["registry:5000"]
    repository: "registry:5000/frontend-image"

- name: e2e-image
  type: docker-image
  source:
    insecure_registries: ["registry:5000"]
    repository: "registry:5000/e2e-image"

- name: backend-repo
  type: git
  source:
    <<: *git-config
    paths:
    - demo/backend
    - demo/ci/tasks/test-and-build-backend.yml
    - demo/ci/scripts/test-and-build-backend.sh
    - demo/ci/manifests/backend.yml

- name: frontend-repo
  type: git
  source:
    <<: *git-config
    paths:
    - demo/frontend
    - demo/ci/tasks/test-and-build-frontend.yml
    - demo/ci/scripts/test-and-build-frontend.sh
    - demo/ci/manifests/frontend.yml

- name: e2e-repo
  type: git
  source:
    <<: *git-config
    paths:
    - demo/frontend/e2e
    - demo/ci/tasks/run-e2e.yml
    - demo/ci/scripts/run-e2e.sh

- name: cf-dev
  type: cf
  source:
    api: https://api.local.pcfdev.io
    username: admin
    password: admin
    organization: pcfdev-org
    space: pcfdev-space
    skip_cert_check: true



#------------------------------------------------------------------------------
#
# Jobs :
# All the jobs that constitue the pipeline.
#
#------------------------------------------------------------------------------
jobs:
- name: build-backend-image
  plan:
  - get: repo
    resource: backend-image-repo
    trigger: true
  - put: backend-image
    params:
      build: repo
      dockerfile: repo/demo/ci/dockerfiles/backend-dockerfile

- name: build-frontend-image
  plan:
  - get: repo
    resource: frontend-image-repo
    trigger: true
  - put: frontend-image
    params:
      build: repo
      dockerfile: repo/demo/ci/dockerfiles/frontend-dockerfile

- name: build-e2e-image
  plan:
  - get: repo
    resource: e2e-image-repo
    trigger: true
  - put: e2e-image
    params:
      build: repo
      dockerfile: repo/demo/ci/dockerfiles/e2e-dockerfile

- name: backend
  plan:
  - get: repo
    resource: backend-repo
    trigger: true
  - get: backend-image
    params:
      skip_download: false
    passed:
    - build-backend-image
  - task: build
    image: backend-image
    file: repo/demo/ci/tasks/test-and-build-backend.yml
  - put: cf-dev
    params:
      manifest: repo/demo/ci/manifests/backend.yml
      path: build/backend.jar

- name: frontend
  plan:
  - get: repo
    resource: frontend-repo
    trigger: true
  - get: frontend-image
    params:
      skip_download: false
    passed:
    - build-frontend-image
  - task: test
    image: frontend-image
    file: repo/demo/ci/tasks/test-and-build-frontend.yml

- name: e2e
  plan:
  - get: repo
    resource: e2e-repo
    trigger: true
  - get: frontend-repo
    passed: [frontend]
    trigger: true
  - get: backend-repo
    passed: [backend]
    trigger: true
  - get: e2e-image
    params:
      skip_download: false
  - task: test
    image: e2e-image
    file: repo/demo/ci/tasks/run-e2e.yml
