config:
- &git-config
  uri: https://github.com/Kehrlann/concourse-demo.git
  branch: master

resources:
- name: backend-image-repo
  type: git
  source:
    <<: *git-config
    paths: [demo/backend/pom.xml, demo/ci/dockerfiles/backend-dockerfile]


- name: backend-image
  type: docker-image
  source:
    insecure_registries: ["registry:5000"]
    repository: "registry:5000/backend-image"

jobs:
- name: build-backend-image
  plan:
  - get: repo
    resource: backend-image-repo
    trigger: true
  - put: backend-image
    params:
      build: repo
      dockerfile: repo/demo/ci/dockerfiles/backend-dockerfile

