version: '3'

services:
  concourse-db:
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse
      POSTGRES_PASSWORD: changeme
      PGDATA: /database

  concourse-web:
    image: concourse/concourse
    links: [concourse-db]
    command: web
    depends_on: [concourse-db]
    ports: ['8080:8080']
    volumes: ['./keys/web:/concourse-keys']
    restart: unless-stopped # required so that it retries until concourse-db comes up
    environment:
      - CONCOURSE_POSTGRES_HOST=concourse-db
      - CONCOURSE_POSTGRES_USER=concourse
      - CONCOURSE_POSTGRES_PASSWORD=changeme
      - CONCOURSE_POSTGRES_DATABASE=concourse
      - CONCOURSE_EXTERNAL_URL=http://concourse.daniel:8080/
      - CONCOURSE_ADD_LOCAL_USER=test:$$2a$$10$$0W9/ilCpYXY/yCPpaOD.6eCrGda/fnH3D4lhsw1Mze0WTID5BuiTW
      - CONCOURSE_MAIN_TEAM_ALLOW_ALL_USERS=true

  concourse-worker:
    image: concourse/concourse
    privileged: true
    links: [concourse-web, registry]
    depends_on: [concourse-web, registry]
    command: worker
    volumes:
      - './keys/worker:/concourse-keys'
    environment:
      - CONCOURSE_TSA_HOST=concourse-web:2222

  registry:
    image: registry:2
    depends_on: [concourse-web]
    volumes:
      - 'registry:/var/lib/registry'
    ports:
      - '5000:5000'

  minio:
    image: minio/minio
    depends_on: [concourse-web]
    ports:
      - '9000:9000'
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: changeme
    command: server /export

volumes:
  registry:
    external: true
