version: '3'

services:
  concourse-db:
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse
      POSTGRES_PASSWORD: changeme
      PGDATA: /database

  concourse-web:
    image: concourse/concourse
    command: web
    depends_on: [concourse-db, vault]
    ports: ['8080:8080']
    volumes: ['./keys/web:/concourse-keys']
    restart: unless-stopped # required so that it retries until concourse-db comes up
    environment:
      - CONCOURSE_POSTGRES_HOST=concourse-db
      - CONCOURSE_POSTGRES_USER=concourse
      - CONCOURSE_POSTGRES_PASSWORD=changeme
      - CONCOURSE_POSTGRES_DATABASE=concourse
      - CONCOURSE_EXTERNAL_URL=http://concourse.daniel:8080/
      - CONCOURSE_ADD_LOCAL_USER=test:test
      - CONCOURSE_MAIN_TEAM_LOCAL_USER=test
      - CONCOURSE_RESOURCE_CHECKING_INTERVAL=5s
      - CONCOURSE_VAULT_URL=http://vault:8200
      - CONCOURSE_VAULT_CLIENT_TOKEN=${VAULT_CLIENT_TOKEN}

  concourse-worker:
    image: concourse/concourse
    privileged: true
    depends_on: [concourse-web, registry, git]
    command: worker
    volumes:
      - './keys/worker:/concourse-keys'
    environment:
      - CONCOURSE_TSA_HOST=concourse-web:2222
      - CONCOURSE_GARDEN_ADDITIONAL_HOST_ENTRY="${MINIKUBE_IP} todo.ci.kube.daniel"

  registry:
    image: registry:2
    volumes:
      - 'registry:/var/lib/registry'
    ports:
      - '5000:5000'

  minio:
    image: minio/minio
    ports:
      - '9000:9000'
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: changeme
    command: server /export

  vault:
    image: vault
    ports: ["8200:8200"]
    environment:
    - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_ADMIN_TOKEN}

  git:
    build:
      context: .
      dockerfile: alpine-ssh-git-dockerfile
    image: kehrlann/ssh-git
    ports: ["2222:22"]
    volumes:
      - "./keys/git:/home/git/.ssh"
      - "../..:/home/git/concourse.git:ro"

volumes:
  registry:
    external: true
